# Fill in the YAML configuration for the microservices 

version: "2.1"
services:
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq" 
    ports:
      - 5672:5672
      - 15672:15672
  producer:
    image: producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    ports: 
      - 5000:5000
    volumes:
      - ./producer:/python-docker/.
    depends_on:
      - rabbitmq
  ride_matching:
    image: consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - producer
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=CUSTOMER_1
      - PRODUCER_ADDRESS=http://producer:5000
  # ride_database:
  #   image: 
  #   container_name:
  #   restart: 
  #   depends_on:
  #     - producer
  