# Fill in the YAML configuration for the microservices 

version: "2.1"
services:
  db:
    container_name: "db"
    build:
      context: ./postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
       
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq" 
    logging:
      driver: none


  producer:
    build:
      context: ./producer
    container_name: producer
    ports: 
      - 5000:5000
    volumes:
      - ./producer:/python-docker/.
    depends_on:
      - rabbitmq

  ride_matching:
    build:
      context: ./consumer
    container_name: consumer
    depends_on:
      - producer
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=CUSTOMER_1
      - PRODUCER_ADDRESS=http://producer:5000

  ride_matching2:
    build:
      context: ./consumer
    container_name: consumer2
    depends_on:
      - producer
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=CUSTOMER_2
      - PRODUCER_ADDRESS=http://producer:5000

  ride_database:
  # image: 
    build:
      context: ./database
    container_name: database 
    depends_on: 
      - producer
      - rabbitmq
      - db
    environment:
    - PYTHONUNBUFFERED=1
    - POSTGRESPSWD=postgres
    - HOST=db