# Fill in the YAML configuration for the microservices 

version: "2.1"
services:
  db:
    container_name: "db"
    # image: postgres:14.1-alpine
    build:
      context: ./postgres_db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #  - '5432:5432'
    # volumes: 
    #   - db:/var/lib/postgresql/data
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
       
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq" 
    ports:
      - 5672:5672
      # - 15672:15672

  producer:
    image: producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    ports: 
      - 5000:5000
    volumes:
      - ./producer:/python-docker/.
    depends_on:
      - rabbitmq

  ride_matching:
    image: consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - producer
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=CUSTOMER_1
      - PRODUCER_ADDRESS=http://producer:5000

  ride_database:
  # image: 
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database 
    depends_on: 
      - producer
      - rabbitmq
      - db
    environment:
    - PYTHONUNBUFFERED=1
    - POSTGRESPSWD=postgres
    #- HOST=host.docker.internal 
    - HOST=db
    links:
      - db
    volumes:
    - './:/src'

  
  
# volumes:
#   db:
#     driver: local